### ISSUE TITLE
Breaking UI in mobile devices

### ISSUE THREAD

**Issue by Rishi-121** [NegiAkash890/editor-frontend#30] opened 2021-12-23 14:02 UTC
![Screenshot (71)](https://user-images.githubusercontent.com/62418363/147250716-6b925cff-113a-4590-a7e8-66cf88af893f.png)

**Comment by Rishi-121** [comment] 2021-12-23 14:02
@NegiAkash890 UI is breaking into mobile devices. I would like to work on this issue.

**Comment by Rishi-121** [comment] 2021-12-23 16:16
@NegiAkash890 , I have created a PR on this issue , PR #31

**Comment by Rishi-121** [comment] 2021-12-23 19:03
@aakankshabhende @NegiAkash890 

PR #31 is already merged. Add this issue as part of SWOC so that it can be evaluated as part of the contribution program.

**Comment by arp99** [comment] 2021-12-24 07:39
> @aakankshabhende @NegiAkash890
> 
> PR #31 is already merged. Add this issue as part of SWOC so that it can be evaluated as part of the contribution program.

The issue is not resolved, I can still see the same issue. @Rishi-121 @NegiAkash890 
![issue1](https://user-images.githubusercontent.com/47218246/147330317-462e4c5a-171b-46a6-b834-1445a41e5254.png)

**Comment by Rishi-121** [comment] 2021-12-24 13:39
Check the PR #31 I have attached the screenshots of the updated UI. @arp99 @NegiAkash890 

May be issue is with the deployment.

**Comment by arp99** [comment] 2021-12-24 16:27
> Check the PR #31 I have attached the screenshots of the updated UI. @arp99 @NegiAkash890
> 
> May be issue is with the deployment.

Yeah I had seen the PR, though the PR was merged to main, I wondered why it didn't change yet, The changes are still not deployed

**Comment by Rishi-121** [comment] 2021-12-25 12:25
This issue is resolved with PR #31 @NegiAkash890 

Changes aren't reflected in production version.

**Comment by NegiAkash890** [comment] 2021-12-25 12:25
> > Check the PR #31 I have attached the screenshots of the updated UI. @arp99 @NegiAkash890
> > May be issue is with the deployment.
> 
> Yeah I had seen the PR, though the PR was merged to main, I wondered why it didn't change yet, The changes are still not deployed

That's because every time a PR is merged I manually deploy the project again and since the PR was merged by @aakankshabhende so she might not have paid attention to this.

**Comment by NegiAkash890** [comment] 2021-12-25 12:26
> This issue is resolved with PR #31 @NegiAkash890
> 
> Changes aren't reflected in production version.

They are now deployed

**Comment by NegiAkash890** [comment] 2021-12-25 12:26
Fixed with #31

**Comment by Rishi-121** [comment] 2021-12-25 12:27
Ok 👍

**Closed by NegiAkash890** 2021-12-25 12:26 UTC
Labels: SWOC, Difficulty : Easy

**Comment by arp99** [comment] 2021-12-25 13:04
Ok looks good😊
